# Generated by Django 4.0.3 on 2022-03-28 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0007_capitol_language_movie_framework_country_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taskapp.band'),
        ),
    ]
