# Generated by Django 4.0.3 on 2022-03-28 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0008_album_band'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='character',
            table='chch',
        ),
    ]
