# Generated by Django 4.0.3 on 2022-03-28 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0009_alter_character_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='character',
            table=None,
        ),
    ]
