# Generated by Django 4.0.3 on 2022-03-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Census',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('sex', models.CharField(blank=True, max_length=1, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('pop2000', models.IntegerField(blank=True, null=True)),
                ('pop2008', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'census',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StateFact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=128, null=True)),
                ('country', models.CharField(blank=True, max_length=128, null=True)),
                ('type', models.CharField(blank=True, max_length=128, null=True)),
                ('sort', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(blank=True, max_length=128, null=True)),
                ('occupied', models.CharField(blank=True, max_length=128, null=True)),
                ('notes', models.CharField(blank=True, max_length=128, null=True)),
                ('fips_state', models.CharField(blank=True, max_length=128, null=True)),
                ('assoc_press', models.CharField(blank=True, max_length=128, null=True)),
                ('standard_federal_region', models.CharField(blank=True, max_length=128, null=True)),
                ('census_region', models.CharField(blank=True, max_length=128, null=True)),
                ('census_region_name', models.CharField(blank=True, max_length=128, null=True)),
                ('census_division', models.CharField(blank=True, max_length=128, null=True)),
                ('census_division_name', models.CharField(blank=True, max_length=128, null=True)),
                ('circuit_court', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'state_fact',
                'managed': False,
            },
        ),
    ]
